// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };
import { esQuery as queryJSON } from "./json.js"
import { baseURL, headers } from "./constants.js";

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseURL: baseURL
  }
});

const payload = JSON.stringify(queryJSON);

export default function() {
  postman[Request]({
    name: "GraphQL top-sound",
    id: "2f528855-0d66-43d1-9f25-a0882abcc640",
    method: "POST",
    address: "{{baseURL}}/graphql",
    data: payload,
    headers: headers
  });
}
